### ISSUE TITLE
One byte occasionally lost when decrypting packets

### ISSUE THREAD

**Issue by william-r-dieter** [ICSec/pyDot11#10]
In several packet captures, decrypted WPA/CCMP/AES packets are almost always 16 bytes shorter than their unencrypted counterparts.  16 bytes makes sense, because the CCMP header is 8 bytes (and it is removed) and the MIC is 8 bytes, and it is removed.

Occasionally, there will be a packet that is 17 bytes shorter (independent of whether decryption succeeds as described in #9).  In this case, the packet headers match, except that the protected bit is cleared in the unencrypted packet and the CCMP header is removed.  The decrypted payload matches Wireshark's version of the decrypted payload -- if you include the first byte of the FCS.  That is, it appears that only three FCS bytes were inserted in the packet.

The original packet is in the following trace: [enc0-153.pcap.gz](https://github.com/ICSec/pyDot11/files/1251131/enc0-153.pcap.gz)
Wireshark is able to dissect it when provided with the EAPOL handshake, the ssid, and the psk:
![enc0-153-decoded](https://user-images.githubusercontent.com/18727218/29704072-01f320c8-892d-11e7-8bf5-d9ebdd97fcfd.png)

Here is a pcap with the decrypted packet: [dec0-153.pcap.gz](https://github.com/ICSec/pyDot11/files/1251132/dec0-153.pcap.gz)

Wireshark can decode it, too, but throws an error on the DNS record for being too short.  Notice that:

1. The decrypted packet is 17 bytes shorter than the encrypted packet (it should be 16 bytes shorter)
2. The first byte of the FCS in the decrypted packet matches the last byte of the decrypted payload in the encrypted packet.
3. Wireshark says the IP payload is 1 byte too short.
 
the ![dec0-153-decoded](https://user-images.githubusercontent.com/18727218/29704167-747d0b90-892d-11e7-9bf2-9f266f6167f1.png)

**Comment by william-r-dieter** [comment]
Pull Request #11, seems to fix this for me.  Hopefully, I have not broken too much else...  It might be a bit cleaner to make fcsGen a class method on Packet, then use it everywhere instead of calling crc32 and struct.pack directly.

**Comment by william-r-dieter** [comment]
@stryngs not sure if you get notified automatically on bug updates, so adding an explicit mention...

**Comment by stryngs** [comment]
@william-r-dieter you still around?

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.
