### ISSUE TITLE
IndexError: Layer [Dot11WEP] not found

### ISSUE THREAD

**Issue by elenabdc** [ICSec/pyDot11#20]
I get that error when trying to decrypt a WPA encrypted packet. I'm using this code:
```origPkt, decodedPkt, PN = wpaDecrypt('Rn4S4-1m3D1r, enc[1], 'ccmp')```

What am I doing wrong?

**Comment by stryngs** [comment]
Hi @elenabdc,

Hard to answer that question without a little bit more knowledge on the backend.  Do you have a PCAP, complete with the EAPOL and a given data packet handy?

**Comment by pcarmo** [comment]
Hello, I'm also having this problem. I guess you're considering all packets have a Dot11WEP layer, which is not happening

**Comment by stryngs** [comment]
@pcarmo Hello.  All packets that were encrypted used to have the Dot11WEP layer.  Now, it is a combination of Dot11WEP and Dot11Encrypted.  I'll try to respark this issue here in a couple days.  Been fairly busy otherwise I would have tried to help out.

**Comment by stryngs** [comment]
@pcarmo @elenabdc I'm going to close this issue back out.  @pcarmo I'll work with you on this via the other Issue.  @elenabdc Feel free to comment if you have questions on this.  Happy to show the whys.
