### ISSUE TITLE
ImportError: No module named wifiEssentials

### ISSUE THREAD

**Issue by lynnux** [ICSec/pyDot11#23]
I manully installed python modules in RESOURCEs using command `python setup.py install`, it seems no error, but got those errors when run `python pyDot11`
```
[root@localhost pyDot11-master]# python pyDot11
Traceback (most recent call last):
  File "pyDot11", line 9, in <module>
    from pyDot11 import *
  File "build/bdist.linux-x86_64/egg/pyDot11/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/pyDot11/lib/ccmp.py", line 10, in <module>
ImportError: No module named wifiEssentials
```
by the way, my machine can't run pip due to offline enviroment.

**Comment by stryngs** [comment]
Hi @lynnux.  When you say offline environment, are you still able to do non internet related downloads?  If so:
pip install pyDot11-1.1.7.tar.gz from within the RESOURCEs folder will do it for you.  If you do it in the order listed, it shouldn't download anything.

If pip is not possible at all, then you'll have to move the modules to where they are in the path as called.

**Comment by stryngs** [comment]
Actually, I need to fix this.  I went back and forth with naming conventions for packetEssentials/wifiEssentials.  Give me a little bit and I'm going to patch.  It's using the wrong name.

**Comment by stryngs** [comment]
@lynnux Patched and ready to go.  Try this:
$ git clone https://github.com/ICSec/pyDot11
Cloning into 'pyDot11'...
remote: Counting objects: 458, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 458 (delta 16), reused 39 (delta 12), pack-reused 408
Receiving objects: 100% (458/458), 11.81 MiB | 2.19 MiB/s, done.
Resolving deltas: 100% (195/195), done.
$ cd pyDot11/
$ cp RESOURCEs/packetEssentials-1.0.8.tar.gz .
$ tar zxf packetEssentials-1.0.8.tar.gz 
$ mv packetEssentials-1.0.8/packetEssentials .
$ python ./pyDot11
usage: pyDot11 [-h] (-i <Sniffing NIC> | -f <Input PCAP>) -b <tgt BSSID>
               [-d <Direction>] [-e <tgt ESSID>] [-n <dev number>] -p
               <Passphrase> -t <Encryption type>
pyDot11: error: argument -b is required



Let me know if the above does not work for you.  I'm glad you had an issue as it turns out, so did lib.subtypes.py...  By asking for help, you made me fix it =)

**Comment by lynnux** [comment]
@stryngs, thank you for your work! Actually, I'm on a new machine without pip installed but with network connected. I'v already installed pip now.
```
[root@localhost py]# git clone https://github.com/ICSec/pyDot11
Cloning into 'pyDot11'...
remote: Counting objects: 469, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 469 (delta 16), reused 39 (delta 12), pack-reused 417
Receiving objects: 100% (469/469), 11.81 MiB | 55.00 KiB/s, done.
Resolving deltas: 100% (195/195), done.
[root@localhost py]# cd pyDot11
[root@localhost pyDot11]# cp RESOURCEs/packetEssentials-1.0.8.tar.gz .
[root@localhost pyDot11]# tar zxf packetEssentials-1.0.8.tar.gz
[root@localhost pyDot11]# mv packetEssentials-1.0.8/packetEssentials .
[root@localhost pyDot11]# ls
LICENSE  packetEssentials  packetEssentials-1.0.8  packetEssentials-1.0.8.tar.gz  PCAPs  pyDot11  README.md  RESOURCEs  scripts  SRC
[root@localhost pyDot11]# python ./pyDot11
Traceback (most recent call last):
  File "./pyDot11", line 6, in <module>
    from scapy.layers.eap import Ether, EAPOL
ImportError: No module named eap

```
so your patch seems OK , but I got an another error, as I know, there has an old version of scapy on this computer, I'll try to fix this on my own. So this issue can be closed now.

**Comment by stryngs** [comment]
That error is because when they released scapy 2.4.0, they modified some of the modules.  You need scapy-2.4.0.

**Comment by stryngs** [comment]
@lynnux That being said, glad it worked for you.  If you need anything further, don't be shy.  Cheers!

**Comment by lynnux** [comment]
@stryngs, after I manully remove the old scapy and use pip installed the scapy 2.4.0, I still got error like:
```
[root@localhost pyDot11]# python pyDot11
Traceback (most recent call last):
  File "pyDot11", line 9, in <module>
    from pyDot11 import *
  File "/usr/local/lib/python2.7/site-packages/pyDot11/__init__.py", line 8, in <module>
    from .lib.ccmp import Ccmp
  File "/usr/local/lib/python2.7/site-packages/pyDot11/lib/ccmp.py", line 10, in <module>
    import wifiEssentials as WE
```
but all errors are gone after `pip install packetEssentials-1.0.8.tar.gz`, so your patch may not work. Then I try to uninstall packetEssentials, but still got pyDot11 work, I don't know why ^_^
```
[root@localhost pyDot11]# pip uninstall packetEssentials
Uninstalling packetEssentials-1.0.8:
  Would remove:
    /usr/local/lib/python2.7/site-packages/packetEssentials-1.0.8.dist-info/*
    /usr/local/lib/python2.7/site-packages/packetEssentials/*
Proceed (y/n)? y
  Successfully uninstalled packetEssentials-1.0.8
[root@localhost pyDot11]# python pyDot11
usage: pyDot11 [-h] (-i <Sniffing NIC> | -f <Input PCAP>) -b <tgt BSSID>
               [-d <Direction>] [-e <tgt ESSID>] [-n <dev number>] -p
               <Passphrase> -t <Encryption type>
pyDot11: error: argument -b is required
```

**Comment by stryngs** [comment]
If you de-tar'd packetEssentials, moved the folder to pyDot11, then Python isn't looking for an installed copy of packetEssentials, it's going to use the module in the folder, i.e. pyDot11/packetEssentials

**Comment by stryngs** [comment]
@lynnux Scapy is definitely one of the better libraries for dealing with frames/packets.  What exactly are you doing with pyDot11?  It's been used a couple different ways.  If you give me ideas of what you're trying to accomplish, I'd be happy to point you right.

**Comment by lynnux** [comment]
@stryngs Actually, I came from another project https://github.com/mfontanini/dot11decrypt. On 2.4G channel, that program runs OK (however, it has a bug on WPA1 to handle the 4th handshake, and I'v already fixed it), but on 5G channel, it only show several ARP packets in tap0. So I switched to this project to do some tests on 5G. 
But saddly, up till now, I can't even get work with 2.4G, only see 
```
EAPOL STARTED: 04:50:da:06:31:dd
EAPOL COMPLETE: 04:50:da:06:31:dd
```
I patched the pyDot11 to add print lines. It seems `pktFilter` return False for most case.

By the way, I reviewed code in ccmp.py `Ccmp::decoder`, they are almost the same as `SessionKeys::ccmp_decrypt_unicast` in mfontanini/dot11decrypt ^_^.

**Comment by stryngs** [comment]
@lynnux I personally haven't worked with the 5GHz band.  If you're seeing EAPOL complete, that means it should be decrypting the data.

When you say you came from dot11decrypt, that's funny.  pyDot11 was born out of the fact that dot11decrypt had some errors, as well as it only did the tap0 thing, versus the way in which you can use pyDot11.

Have you had a chance to look at airpwn-ng yet by chance?
