### ISSUE TITLE
Had an issue with grabbing EAPOL

### ISSUE THREAD

**Issue by devdwy** [ICSec/pyDot11#40]
Hi, the EAPOL extraction wasn't working for me so I had to debug the issue. It turns out that my pcap was returning capitalized hex strings during byteRips. The code is not taking that into consideration so there are two places where string comparison fails (in handshake.py, lines 55 and 94)

I added ".lower()" to the two locations and it worked:

`eNum = self.pt.nonceDict.get(self.pt.byteRip(pkt[Raw], qty = 3)[6:].lower())`

`encType = self.pt.byteRip(pkt[Raw], qty = 3)[3:].lower()`

If I have time I will create a PR.

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.
