### ISSUE TITLE
Decrypting WPA2-Personal CCMP Key

### ISSUE THREAD

**Issue by Stemp123** [ICSec/pyDot11#41]
I'm really sorry I posted this as an issue but I didn't find a way to contact you. I hope I can remove the "issue" afterwards. 

I need to decrypt a  WPA2-Personal CCMP Key but dont know how I run this script. Can I sen you the key to you so you can try to decrypt it?

I know this sounds really nooby and I apologize in advance. 

Discord: Sten#6293 Telegram: @Freshweiner

**Comment by stryngs** [comment]
Hi @Stemp123 -- Happy to help.  I don't have Discord or Telegram but I do use IRC.  Whats your timezone?

**Comment by Stemp123** [comment]
Hey I asked a few other people and since the key is from another computer on which i don't have admin privileges they said it's next to impossible to decrypt the key without bruteforcing it. Do you know if this is tru, that I should give up?

**Comment by stryngs** [comment]
Hi @Stemp123 -- email me [at] --> support[at]configitnow.com

**Comment by stryngs** [comment]
Closing this out as you must know certain information to legally use this tool.  Cheers!
