### ISSUE TITLE
install pycryptodomex error in Win10 python.3.8.7

### ISSUE THREAD

**Issue by donPab** [ICSec/pyDot11#42]
C:\H_Paul\Win10\pyDot11-master>pip install RESOURCEs/pycryptodomex-3.4.5.tar.gz
---then after 690 or so lines---
    Copying file build\lib.win-amd64-3.8\Crypto\Util\_raw_api.py to build\lib.win-amd64-3.8\Cryptodome\Util\_raw_api.py
    Copying file build\lib.win-amd64-3.8\Crypto\Util\__init__.py to build\lib.win-amd64-3.8\Cryptodome\Util\__init__.py
    running build_ext
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python387\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paul-lap\\AppData\\Local\\Temp\\pip-req-build-puhzkjby\\setup.py'"'"'; __file__='"'"'C:\\Users\\paul-lap\\AppData\\Local\\Temp\\pip-req-build-puhzkjby\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\paul-lap\AppData\Local\Temp\pip-record-s5uma9xc\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python387\Include\pycryptodomex' Check the logs for full command output.

C:\H_Paul\Win10\pyDot11-master>

     command: 'c:\python387\python.exe' -u -c 'import sys, setuptools, tokenize; 
sys.argv[0] = '"'"'C:\\Users\\paul-lap\\AppData\\Local\\Temp\\pip-req-build-puhzkjby\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\paul-lap\\AppData\\Local\\Temp\\pip-req-build-puhzkjby\\setup.py'"'"';
f=getattr(tokenize, '"'"'open'"'"', open)(__file__);
code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');
f.close();
exec(compile(code, __file__, '"'"'exec'"'"'))' 
  install 
    --record 'C:\Users\paul-lap\AppData\Local\Temp\pip-record-s5uma9xc\install-record.txt' 
    --single-version-externally-managed 
    --compile 
    --install-headers 'c:\python387\Include\pycryptodomex'

         cwd: C:\Users\paul-lap\AppData\Local\Temp\pip-req-build-puhzkjby\

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.

**Comment by stryngs** [comment]
@donPab Real quick I noticed the C:\.  That tells me you aren't on Linux and pyDot11 is not geared towards windows support.  if you want that you have to dive down the airpcap card route.  I don't recommend that path.

**Comment by donPab** [comment]
Hi stryngs,

Thanks for the review of the problem.

What is a PR? (?pull request?) It sounds like a solution that I would propose?

But I have no solution, only a recognized problem.  

And you just told me that it wasn’t meant for “Windows”.

 

Does yours work in Win10? Is your fork stable and preferred over ICSec?

What level of python is it running on?

I may give it a try.

Tkx, donPab

**Comment by stryngs** [comment]
Hi @donPab so pyDot11 came from airpwn-ng.  Eventually I split it off, but since the development arose out of ICSec, it just became a remnant.  In order to not have to do 2 git pushes when I update, I split out pyDot11 and packetEssentials pointing to my own copies of the repos.

Now on the windows things, pyDot11 was never meant for it, nor is it likely to be supported in the future; Windows makes it hard to sniff packets in monitor mode, let alone the trouble to injecting them.

Boot up in linux though and yuo'd be good to go =)
